development:
  adapter: mysql2
  host: 127.0.0.1
  database: hui_dev
  pool: 5
  username: root
  password: '123456'
  socket: /var/run/mysqld/mysqld.sock
  encoding: utf8

test: &test
  adapter: mysql2
  host: 127.0.0.1
  database: hui_test
  pool: 5
  username: root
  password: '123456'
  timeout: 5000
  encoding: utf8

production:
  adapter: mysql2
  host: 127.0.0.1
  database: hui_pro
  pool: 5
  username: root
  password: '123456'
  timeout: 5000
  encoding: utf8

cucumber:
  <<: *test
